from pymongo import MongoClient
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_mongodb import MongoDBAtlasVectorSearch
from langchain_community.document_loaders import DirectoryLoader
from langchain_core.prompts import ChatPromptTemplate

import gradio as gr
import key_param

client = MongoClient(key_param.MONGO_URL)
dbName = "longchain_demo"
collectionName = "collection_of_text_blobs"
collection = client[dbName][collectionName]

# Define the openAi embeddings model we want to use 
embeddings = OpenAIEmbeddings(openai_api_key=key_param.open_api_key)
# Get access to our Atlass vector store
vectorStore = MongoDBAtlasVectorSearch(collection, embeddings, index_name="vector_index")

# The user will send a query
# This function is designed to process the query and retrieve relevant information using some different tools 
def query_data(query, progress=gr.Progress()):
    if not query:
        return "Please enter a question.", "Please enter a question."
    
    progress(0, desc="Starting...")
    #Convert the input query into a vector using openai embeddings model (k=1==> we are going to retrieve the most similar document)
    # It is going to perform a vector search using langchain vector store API
    docs = vectorStore.similarity_search(query, k=1)
   
    if not docs:
        return "No documents found.", "No documents found."
    
    progress(0.3, desc="Processing vector search...")
    ## We are going to return the content of the most relevant document directly as output
    #--> Extract the page content from the top documents return list, wich is the most relevant information in our original query
    as_output= docs[0].page_content

    # Define a llm model using OpenAI API
    # temperature=0 ==> means the model responds with more deterministic and less creative
    llm = ChatOpenAI(openai_api_key=key_param.open_api_key, temperature=0)
    
    progress(0.5, desc="Retrieving documents...")
    # Initialise a retriver for mongodb vectorStore
    # This retriever is responsible for fecthing documents that are relevant to our query
    retriever = vectorStore.as_retriever()
    
    # This chain is then executed with our original query
    # This process involves llm generating responses based on the documents retrieved and the nature of the query
    retrieved_docs = retriever.invoke(query)
    context = "\n\n".join([doc.page_content for doc in retrieved_docs])
    progress(0.7, desc="Generating response...")
    prompt = ChatPromptTemplate.from_template("{context}\n\nQuestion: {input}")
    messages = prompt.format_messages(context=context, input=query)
    retriever_output = llm.invoke(messages).content

    ## Return both the direct document content and the llm-generated response based on the retrieved documents
    # Then the fuunction will return two outputs
    # 1- The as_output ==> wich is content of the most similiar document from the atlas vector search
    # 2- The retriever_output ==> wich is the output generated by the retriver qa_chain using the RAG architecture
    return as_output, retriever_output

with gr.Blocks(title="Question Answering App using MongoDB Atlas Vector Search + RAG (Langchain)") as demo:
    gr.Markdown("# 🦜🔗 Question Answering App using Atlas Vector Search + RAG Architecture")
    gr.Markdown(
        """
        This app allows you to ask questions based on the content of the documents stored in the MongoDB Atlas Vector Search.
        Simply enter your question below and click 'Submit' to get answers!
        """
    )
    textbox = gr.Textbox(label="Enter your question here :", placeholder="Type your question...")
    with gr.Row():
        button = gr.Button("Submit", variant="primary")
    with gr.Row():
        with gr.Column():
            output1 = gr.Textbox(label="Output with just Atlas Vector Search", lines=10, max_lines=None)
        with gr.Column():
            output2 = gr.Textbox(label="Output generated by chaining Atlas Vector Search to Langchain's RetriverQA + OpebAI LLM:(RAG Architecture)", lines=10, max_lines=None)

    button.click(fn=query_data, inputs=textbox, outputs=[output1, output2])

demo.launch()